In [1]:
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt

**Introduction to Tensors**


datatype = precision in computing (less accuracy, faster computation) \
device = cuda (GPU), CPU \
requires_grad = whether or not to track gradients

In [2]:
#create random torch
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2921, 0.5022, 0.9168, 0.4967],
        [0.4257, 0.9635, 0.7805, 0.7369],
        [0.5166, 0.8546, 0.2505, 0.7970]])

In [3]:
#tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
#tensor of all ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
#torch arange
one_to_ten = torch.arange(start = 0, end = 11, step= 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#creating tensors like = same shape as inputted tensor
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
#create tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10
torch.add(tensor, 10)

tensor([11, 12, 13])

In [8]:
#multiply by 10
tensor * 10
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [9]:
#Matrix Multiplication 
torch.matmul(tensor, tensor)
tensor @ tensor 

tensor(14)

In [10]:
#Transpose
tensor2 = torch.rand(size = (3, 2))
tensor2

tensor([[0.8068, 0.2721],
        [0.7183, 0.5526],
        [0.6328, 0.0597]])

In [11]:
#Transpose
tensor2.T

tensor([[0.8068, 0.7183, 0.6328],
        [0.2721, 0.5526, 0.0597]])

In [12]:
#min, max, avg 
torch.min(tensor)

tensor(1)

In [13]:
#Max
tensor.max()

tensor(3)

In [14]:
#mean: need float 
torch.mean(tensor.type(torch.float64))

tensor(2., dtype=torch.float64)

In [15]:
#sum
tensor.sum()

tensor(6)

In [16]:
#finding positional min
tensor.argmin()

tensor(0)

In [17]:
#finding positional max
tensor.argmax()

tensor(2)

In [18]:
#reshaping: reshapes an input tensor to desired shape 
import torch
x = torch.arange (1., 10.)
#add extra dim
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [19]:
#view: return of view of an input tensor of a certain shape, keep the same memory
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [20]:
#changing z changes x
z[:,0] = 99
z, x

(tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [21]:
#stach: combne multiple tensors on top of each other (vstack) or side by side (hstack)
x = torch.arange (1., 10.)
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked, x_stacked.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [22]:
#squeeze - removes all "1" dimensions from a tensor
x_reshaped.squeeze()

tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [23]:
#unsqueeze - add "1" dimension from a tensor
x_reshaped.unsqueeze(dim = 2)

tensor([[[99.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]]])

In [24]:
#permuete: return a 'view' of the input with dimensions permuted in a certain way
x_org = torch.rand(size = (224, 100, 3))
torch.permute(x_org, (2, 0, 1)).shape #shits axis 0 -> 1, 1 -> 2, 2 -> 0

torch.Size([3, 224, 100])

In [25]:
#indexing (selecting data from tesnors)
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [26]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
x[0][0]

tensor([1, 2, 3])

In [28]:
x[0][0][0]

tensor(1)

In [29]:
# use ":" to select all of the target dim
x[:, 0]

tensor([[1, 2, 3]])

In [30]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [3]:
#create a tensor (default on CPU)

tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [5]:
device = 'cuda'
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Numpy only works on cpu

In [6]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])